//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""UserInputs"",
            ""id"": ""c143d69c-4d3d-4897-86fc-b3d484c16fa9"",
            ""actions"": [
                {
                    ""name"": ""BackButton"",
                    ""type"": ""Button"",
                    ""id"": ""bc24d86b-aefc-4216-9382-bfc9d5e9a483"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2f07fc63-3a2a-4157-9950-cd6126071109"",
                    ""path"": ""<Keyboard>/{Back}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UserInputs
        m_UserInputs = asset.FindActionMap("UserInputs", throwIfNotFound: true);
        m_UserInputs_BackButton = m_UserInputs.FindAction("BackButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UserInputs
    private readonly InputActionMap m_UserInputs;
    private List<IUserInputsActions> m_UserInputsActionsCallbackInterfaces = new List<IUserInputsActions>();
    private readonly InputAction m_UserInputs_BackButton;
    public struct UserInputsActions
    {
        private @Inputs m_Wrapper;
        public UserInputsActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @BackButton => m_Wrapper.m_UserInputs_BackButton;
        public InputActionMap Get() { return m_Wrapper.m_UserInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserInputsActions set) { return set.Get(); }
        public void AddCallbacks(IUserInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_UserInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UserInputsActionsCallbackInterfaces.Add(instance);
            @BackButton.started += instance.OnBackButton;
            @BackButton.performed += instance.OnBackButton;
            @BackButton.canceled += instance.OnBackButton;
        }

        private void UnregisterCallbacks(IUserInputsActions instance)
        {
            @BackButton.started -= instance.OnBackButton;
            @BackButton.performed -= instance.OnBackButton;
            @BackButton.canceled -= instance.OnBackButton;
        }

        public void RemoveCallbacks(IUserInputsActions instance)
        {
            if (m_Wrapper.m_UserInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUserInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_UserInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UserInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UserInputsActions @UserInputs => new UserInputsActions(this);
    public interface IUserInputsActions
    {
        void OnBackButton(InputAction.CallbackContext context);
    }
}
